# Generated by Django 3.0.3 on 2020-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='hello', verbose_name='/projects/static/img'),
            preserve_default=False,
        ),
    ]
