# Generated by Django 3.0.3 on 2020-02-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200212_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
    ]
