# Generated by Django 3.0.3 on 2020-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta',
            field=models.CharField(default='WIP', max_length=110),
            preserve_default=False,
        ),
    ]
