# Generated by Django 3.0.3 on 2020-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20200212_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='meta',
            field=models.CharField(default='WIP', max_length=100),
            preserve_default=False,
        ),
    ]
